sudo: false
language: python
before_script:
- pip install tox

# test script
script:  tox
notifications:
  on_success: change
  on_failure: always

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-flake8_2.5
    - python: 2.7
      env: TOXENV=py27-flake8_2.6
    - python: 2.7
      env: TOXENV=py27-flake8_3
    - python: 3.3
      env: TOXENV=py33-flake8_2.5
    - python: 3.3
      env: TOXENV=py33-flake8_2.6
    - python: 3.3
      env: TOXENV=py33-flake8_3
    - python: 3.4
      env: TOXENV=py34-flake8_2.5
    - python: 3.4
      env: TOXENV=py34-flake8_2.6
    - python: 3.4
      env: TOXENV=py34-flake8_3
    - python: 3.5
      env: TOXENV=py35-flake8_2.5
    - python: 3.5
      env: TOXENV=py35-flake8_2.6
    - python: 3.5
      env: TOXENV=py35-flake8_3
    - python: pypy
      env: TOXENV=pypy-flake8_2.5
    - python: pypy
      env: TOXENV=pypy-flake8_2.6
    - python: pypy
      env: TOXENV=pypy-flake8_3
    - python: 2.7
      env: TOXENV=readme
    - python: 3.4
      env: TOXENV=flake8
    - python: 3.4
      env: TOXENV=pylint
    - python: 3.4
      env: TOXENV=bandit
